### ISSUE TITLE
PyNaCl library needed but already installed

### ISSUE THREAD

**Issue by Maclean-D** [hc20k/LLMChat#12]
To join a voice channel it's claiming it needs the PyNaCl library but it's already installed. I've run the update.py all the way through without errors but it throws this when trying to join a voice channel:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/root/LLMChat/llmchat/client.py", line 534, in on_voice_state_update
    vc: discord.VoiceClient = await after.channel.connect()
  File "/usr/local/lib/python3.9/dist-packages/discord/abc.py", line 1898, in connect
    voice: T = cls(client, self)
  File "/usr/local/lib/python3.9/dist-packages/discord/voice_client.py", line 239, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice
```

Version of PyNaCl:
```
root@macd-ubuntu-s-1vcpu-1gb-intel-sfo3-01:~/LLMChat# pip show pynacl
Name: PyNaCl
Version: 1.3.0
Summary: Python binding to the Networking and Cryptography (NaCl) library
Home-page: https://github.com/pyca/pynacl/
Author: The PyNaCl developers
Author-email: cryptography-dev@python.org
License: Apache License 2.0
Location: /usr/lib/python3/dist-packages
Requires:
Required-by:
root@macd-ubuntu-s-1vcpu-1gb-intel-sfo3-01:~/LLMChat#
```

**Comment by Maclean-D** [comment]
Needed newer version nevermind
