### ISSUE TITLE
Toggle Audiobook mode via Discord /command

### ISSUE THREAD

**Issue by Maclean-D** [hc20k/LLMChat#14]
Feature Request:
Add the ability to toggle audiobook mode via / command

**Comment by hc20k** [comment]
Added! 👍

**Comment by Maclean-D** [comment]
Thanks! Also I noticed right now it only works when the bot is in a voice channel.
```
Traceback (most recent call last):
  File "/root/llmc_env/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/root/llmc_env/lib/python3.10/site-packages/discord/app_commands/commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/root/llmc_env/lib/python3.10/site-packages/discord/app_commands/commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'audiobook_mode' raised an exception: AttributeError: 'NoneType' object has no attribute 'is_connected'
```

**Comment by hc20k** [comment]
Ooh good catch! Pushing a fix right now
