### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dillfrescott** [hc20k/LLMChat#19]
```
Traceback (most recent call last):
  File "C:\Users\micro\miniconda3\envs\llmchat\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\micro\Downloads\LLMChat\llmchat\client.py", line 508, in on_ready
    await self.setup_tts()
  File "C:\Users\micro\Downloads\LLMChat\llmchat\client.py", line 148, in setup_tts
    from tts_sources.bark import Bark
  File "C:\Users\micro\Downloads\LLMChat\llmchat\tts_sources\bark.py", line 18, in <module>
    "path": os.environ.get("SUNO_TEXT_MODEL_PATH", os.path.join(bark.generation.REMOTE_BASE_URL, "text.pt")),
AttributeError: module 'bark.generation' has no attribute 'REMOTE_BASE_URL'
```

**Comment by dillfrescott** [comment]
I fixed it by switching to another method!
