### ISSUE TITLE
Discord Audio Client error

### ISSUE THREAD

**Issue by mohemish9** [hc20k/LLMChat#21]
[11-01 22:52:22] [client.py:515] ERROR - Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/LLMChat/llmchat/client.py", line 562, in on_voice_state_update
    vc.listen(self.sink)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/voice_client.py", line 704, in listen
    raise ClientException("Must initialize audio processing pool before listening.")

Steps to replicate :
1. speech_recognition_service = whisper
2. I ran python3 update.py -y and installed everything
3. I ran python3 main.py
4. I join a VC on the server and the bot joined
5. error message above is shown and bot is still in the channel but silent

**Comment by imohitmayank** [comment]
Getting the same error. Anyone able to make it work?
