### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'AudioSink'

### ISSUE THREAD

**Issue by LotEep** [hc20k/LLMChat#28]
On first installation, running main.py returns the following error:

`Traceback (most recent call last):
  File "/home/bob/LLMChat/main.py", line 6, in <module>
    from client import DiscordClient
  File "/home/bob/LLMChat/llmchat/client.py", line 16, in <module>
    from voice_support import BufferAudioSink
  File "/home/bob/LLMChat/llmchat/voice_support.py", line 12, in <module>
    class BufferAudioSink(discord.AudioSink):
                          ^^^^^^^^^^^^^^^^^
AttributeError: module 'discord' has no attribute 'AudioSink'`

OS: Arch Linux
What I have done: I remember fixing this error before somehow, but I forgot what I did to fix it. After fixing this error I got Another error, and did something to try to fix it but it only caused this error to come back again.

This is that other error that shows up after I fixed this one:
` Traceback (most recent call last):
  File "/home/bob/LLMChat/main.py", line 6, in <module>
    from client import DiscordClient
  File "/home/bob/LLMChat/llmchat/client.py", line 7, in <module>
    from discord import app_commands
  File "/home/bob/pythonvenv/lib/python3.12/site-packages/discord/app_commands/__init__.py", line 12, in <module>
    from .commands import *
  File "/home/bob/pythonvenv/lib/python3.12/site-packages/discord/app_commands/commands.py", line 51, in <module>
    from ..enums import SlashCommandOptionType, AppCommandType, ChannelType, Locale
ImportError: cannot import name 'AppCommandType' from 'discord.enums' (/home/bob/pythonvenv/lib/python3.12/site-packages/discord/enums.py)`

**Comment by IloveCock69420** [comment]
Have you tried sucking a big fat cock?
It sometimes works for me...
